services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    init: true
    volumes:
      - type: bind
        source: /opt/tempo-small-server/config.json
        target: /app/config.json
        read_only: true
        bind:
          create_host_path: false
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"