name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug PATH
        run: echo $PATH

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DROPLET_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 147.182.224.36 >> ~/.ssh/known_hosts

      - name: Deploy to Droplet
        run: |
          ssh -v -i ~/.ssh/id_rsa root@147.182.224.36 "
          cd ./bot/Tempo-Sapphire &&
          git pull origin main &&
          npm install &&
          npm start
          "
